<?php

namespace Rotalia\API\Controller;

use App\Entity\CreditNetting;
use App\Entity\User;
use App\Repository\CreditNettingRepository;
use App\Repository\CreditNettingRowRepository;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Container\ContainerExceptionInterface;
use Psr\Container\NotFoundExceptionInterface;
use App\Component\HttpFoundation\JSendResponse;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use Throwable;

/**
 * Read/update access to CreditNetting snapshots. Snapshots themselves are generated by the
 * `app:credit-netting` console command (App\Command\CreditNettingCommand), not by this
 * controller.
 */
class CreditNettingsController extends DefaultController
{
    /**
     * @throws ContainerExceptionInterface
     * @throws NotFoundExceptionInterface
     * @throws Throwable
     */
    #[Route('/creditNettings', methods: ['GET'])]
    public function list(CreditNettingRepository $creditNettingQuery): JsonResponse
    {
        $this->requireAdmin();

        /** @var CreditNetting[] $creditNettings */
        $creditNettings = $creditNettingQuery->createQueryBuilder('c')
            ->orderBy('c.createdAt', 'DESC')
            ->getQuery()
            ->getResult()
        ;

        return $this->json(['creditNettings' => $creditNettings]);
    }

    /**
     * @throws ContainerExceptionInterface
     * @throws NotFoundExceptionInterface
     * @throws Throwable
     */
    #[Route('/creditNettings/{id}', methods: ['PATCH'])]
    public function update(
        EntityManagerInterface $em,
        CreditNettingRowRepository $creditNettingRowQuery,
        Request $request,
        int $id,
    ): JsonResponse
    {
        $this->requireAdmin();

        /** @var User $user */
        $user = $this->getUser();
        $memberConventId = $user->getMember()->getConventId();
        $conventId = (int)$request->request->get('conventId', $memberConventId);

        if ($conventId !== $memberConventId && !$this->isGranted(User::ROLE_SUPER_ADMIN)) {
            return JSendResponse::createFail('Teise konvendi tasaarveldusi saab muuta ainult super admin', 403);
        }

        $creditNettingRow = $creditNettingRowQuery->findOneBy([
            'convent' => $conventId,
            'creditNetting' => $id,
        ]);

        if ($creditNettingRow === null) {
            return JSendResponse::createFail('Tasaarveldust ei leitud', 404);
        }

        $rowData = $request->request->all('creditNettingRow');

        if (array_key_exists('nettingDone', $rowData)) {
            $creditNettingRow->setNettingDone((bool)$rowData['nettingDone']);
        }

        $em->persist($creditNettingRow);
        $em->flush();

        return $this->json(['creditNetting' => $creditNettingRow->getCreditNetting()]);
    }
}
